---
- include_tasks: setup.yml
- include_tasks: config.yml
- include_tasks: log_cleanup.yml
- include_tasks: firewall.yml

- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: restarted
    enabled: "{{ logstash_enabled_on_boot }}"
  notify: restart logstash